spring:
  # 发送邮件配置
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 465 # smtp 服务器的端口
    username: kiwi66@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: tkzqvtmsqqokcbea # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 370610613@qq.com # 发送方邮件，配在yml中可方便更改
